name: dietyuk
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  http: ^0.12.2
  cupertino_icons: ^1.0.2
  flutter_icons: ^1.1.0
  imagebutton: ^0.0.6
  shared_preferences: ^0.5.6
  image_picker: 0.5.0+3
  fluttertoast: ^8.0.7
  simple_animations: ^1.3.3
  intl: ^0.17.0
  rflutter_alert: ^1.0.3
  font_awesome_flutter: ^8.10.0
  google_fonts: ^1.1.1
  badges: ^2.0.1
  flutter_screenutil: ^1.0.2
  hexcolor: ^2.0.4
  charts_flutter: ^0.11.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/images/logo.png
    - assets/images/avatar.png
    - assets/images/pria.jpg
    - assets/images/wanita.png
    - assets/images/bfull.png
    - assets/images/bkosong.png
    - assets/images/bstengah.png
    - assets/images/topup.png
    - assets/images/withdraw.png
    - assets/images/edit.png
    - assets/images/saldo.png
    - assets/images/breakfast.png
    - assets/images/awalpage.png
    - assets/images/awalpage2.png
    - assets/images/awalpage3.png
    - assets/images/awalpage4.png
    - assets/images/awalpage5.png
    - assets/images/dinner.png
    - assets/images/lunch.png
    - assets/images/gym.png
    - assets/images/loginpage.png
    - assets/images/registerpage.png
    - assets/images/mypaket.png
    - assets/images/listpaket.png
    - assets/images/listproduk.png
    - assets/images/header.png
    - assets/images/report.png
    - assets/images/gambarproduk.jpg
    - assets/images/cancel.png
    - assets/images/done.png
    - assets/images/progress.png
    - assets/images/waiting.png
    - assets/images/bni.jpg
    - assets/images/bca.png
    - assets/images/mandiri.png
    - assets/images/equals.png


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: PoiretOne
      fonts:
        - asset: fonts/PoiretOne-Regular.ttf
    - family: Biryani
      fonts:
        - asset: fonts/Biryani-Regular.ttf
        - asset: fonts/Biryani-ExtraLight.ttf
          weight: 200
    - family: Nisebuschgardens
      fonts:
        - asset: fonts/Nisebuschgardens.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
